### ISSUE TITLE
Incompatible version of CryptoPP from brew (OS X) when installing Eth

### ISSUE THREAD

**Issue by mati21** [ethereum/webthree-umbrella#107]
I have been trying to install Eth using homebrew but I get the following:

> ==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PR
> Last 15 lines from /Users/md/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
> -- LevelDB headers: /usr/local/include
> -- LevelDB lib   : /usr/local/lib/libleveldb.dylib
> CMake Error at webthree-helpers/cmake/FindPackageHandleStandardArgs.cmake:138 (message):
>   **Could NOT find CryptoPP: Found unsuitable version "5.6.3", but required is**
>   **exact version "5.6.2" (found /usr/local/include)**
> Call Stack (most recent call first):
>   webthree-helpers/cmake/FindPackageHandleStandardArgs.cmake:372 (_FPHSA_FAILURE_MESSAGE)
>   webthree-helpers/cmake/FindCryptoPP.cmake:107 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   webthree-helpers/cmake/UseCryptopp.cmake:2 (find_package)
>   webthree-helpers/cmake/EthDependencies.cmake:105 (eth_apply)
>   libweb3core/libdevcrypto/CMakeLists.txt:8 (eth_use)

I was trying to find a way to downgrade CryptoPP to 5.6.2 with brew to no avail.

**Comment by shomanishikawa** [comment]
I am also running into this error, when running `brew install cpp-ethereum --with-gui`

I have tried to build my own 5.6.2 release of CryptoPP, but it seems the brew always automatically installs 5.6.3

**Comment by shomanishikawa** [comment]
@mati21 I managed to fix this by forcing homebrew to install a specific commit of cryptopp:

```
cd /usr/local/Library
brew unlink cryptopp
brew uninstall cryptopp
brew cleanup
git checkout d7c2787e9d950b2b5f890afc066aacbf8c2c4974 /usr/local/Library/Formula/cryptopp.rb
brew install cryptopp
```

you're checking out the commit hash for version 5.6.2, which can be seen with `brew log cryptopp`

Confirm with `brew info cryptopp` - should return 5.6.2

Hope that helps!

**Comment by jeanbapt** [comment]
Same error with cryptopp here. Thank you for the tip but I got :
git checkout d7c2787e9d950b2b5f890afc066aacbf8c2c4974 /usr/local/Library/Formula/cryptopp.rb
fatal: reference is not a tree: d7c2787e9d950b2b5f890afc066aacbf8c2c4974
so I am checking the commit hash of 5.6.2. Solved with a full git fetch

**Comment by krisodimitrov** [comment]
I have the same problem and got the same error as @jeanbapt  when I tried with the solution provided by  @shomanishikawa . How can I do a full git fetch? Tried with
git fetch d7c2787e9d950b2b5f890afc066aacbf8c2c4974 /usr/local/Library/Formula/cryptopp.rb

and get the following:

fatal: Invalid refspec '/usr/local/Library/Formula/cryptopp.rb'

**Comment by bobsummerwill** [comment]
I'm now trying this, which seems fairly happy:

```
brew switch cryptopp 5.6.2
brew install cpp-ethereum
```

As https://github.com/Homebrew/homebrew/commits/master/Library/Formula/cryptopp.rb, it appears that the Formula was updated 10 days ago to 5.6.3, and that is what has pooched the eth build, because the CMake build process requires a specific version.

**Comment by bobsummerwill** [comment]
This appears to be the canonical StackOverflow post of the topic:
http://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula

**Comment by bobsummerwill** [comment]
Switch requires you to have installed the package PRIOR to the Formula getting updated, so that isn't a repeatable solution.    We're still missing a repeatable solution here.   Looks like there are a variety of horrible ones.

**Comment by bobsummerwill** [comment]
The _best_ solution is probably adding CryptoPP as a sub-module to webthree-umbrella, so that we get away from platform-specific packaging systems entirely.

See https://github.com/doublethinkco/webthree-umbrella-cross/issues/46 and https://github.com/doublethinkco/webthree-umbrella-cross/issues/47.

**Comment by bobsummerwill** [comment]
So I think this will work. Could you try, @krisodimitrov?

```
git checkout 29509ca $(brew --prefix)/Library/Formula/cryptopp.rb
brew reinstall cryptopp
```

**Comment by subtly** [comment]
Can we update the cmake files to support 5.6.\* where \* is > 1?  Not sure what's required for brew recipe, @caktux might know.

**Comment by bobsummerwill** [comment]
It looks like the versions for some external packages in the CMake files have been locked to specific versions for "a long time", though the pattern is very heterogenous:

See this snapshot from August 2015, prior to refactoring which moved these around:

https://github.com/ethereum/webthree-helpers/blob/e2bd5cab4a71b2b4cbe9a809be7caa82e7b8e903/EthDependencies.cmake

ie.

find_package (CryptoPP 5.6.2 EXACT REQUIRED)
find_package (LevelDB REQUIRED)
find_package(MHD)

**Comment by bobsummerwill** [comment]
My natural inclination here is to suggest that ALL packages should be locked to particular versions in the CMake files unless there is an exceedingly good reason.    Not doing so just introduces extra variables which we don't control.   Similarly, the "package manager" command-line examples we give per platform should explicitly use those versions.

Where this appears to be falling down for homebrew is that unless I am missing something it appears to have NO FIRST CLASS SUPPORT for versioning whatsoever.   You just "brew install X", and that's going to give you whatever the HEAD commit .rb file for that package says.     In this particular example, there is no specific syntax for doing "brew install cryptopp 2.6.4".

Or ... as I said earlier, the best of the best, IMHO, would be to add sub-modules for them all, so we're not dependent on platform-specific package managers at all.

**Comment by bobsummerwill** [comment]
Or in the short-term, maybe MacPorts _does_ support explicit versions, and we just drop support for homebrew and only support MacPorts?

**Comment by bobsummerwill** [comment]
Another short-term fix would be to bump the REQUIRED EXACT version for CryptoPP to 5.6.3 for all platforms, if that version is available in common Ubuntu versions.

Essentially, with homebrew's lack of versioning discipline, our builds worked by co-incidence for Homebrew.    Any of our explicitly versioned packages on Brew will break whenever Brew Formulas are updated.

**Comment by bobsummerwill** [comment]
Chatting it up with Homebrew developers on Twitter:
https://twitter.com/BobSummerwill/status/684097241645068290

**Comment by bobsummerwill** [comment]
See https://github.com/ethereum/webthree-helpers/pull/81.   This is a PR which loosens up the versioning check.   It appears to "work", but I'm not particularly comfortable with the approach at all.   We need stricter versioning, not looser versioning.   But this is probably a rational interim solution.    We'll need to get this change merged, and then webthree-umbrella sub-module updated, and then it looks like the automation will update the homebrew formula.  Correct?

**Comment by bobsummerwill** [comment]
See also http://solidity.readthedocs.org/en/latest/installing-solidity.html.

**Comment by bobsummerwill** [comment]
See https://github.com/ethereum/webthree-umbrella/issues/117 for the latest-and-greatest on getting brew into a healthy state.

**Comment by bobsummerwill** [comment]
Hey @mati21!   This has been addressed now.
Please can you try a fresh install, and report back?   Thanks!

**Comment by bobsummerwill** [comment]
Please can we close this, @chriseth, as per https://github.com/ethereum/webthree-umbrella/issues/117?  Thanks!
