### ISSUE TITLE
AlethOne stuck at block 1150006

### ISSUE THREAD

**Issue by sjaith** [ethereum/webthree-umbrella#368]
AlethOne synced up to 1150006, then stopped syncing

**Comment by bobsummerwill** [comment]
Hey @sjaith!
We need a lot more information than this to be able to do anything, I'm afraid.

What OS?   What version?   Did you built it yourself?   Use installer?

What you done to try to resolve it?   Have you shut down and restarted the app?   Tried rebooting?    Tried waiting?   Thanks!

**Comment by chriseth** [comment]
Most probably a duplicate of https://github.com/ethereum/webthree-umbrella/issues/363
Does restarting AlethOne fix it?

**Comment by sjaith** [comment]
No, I tried a couple times, I also reinstalled, it is still stuck on 1150006Mac OSX 10.11.3, NVIDIA GeForce GTX 780M 4096 MB
Thanks,Steve

```
  From: chriseth <notifications@github.com>
```

 To: ethereum/webthree-umbrella webthree-umbrella@noreply.github.com 
Cc: Steve Austin sjaith@yahoo.com
 Sent: Thursday, March 17, 2016 5:07 PM
 Subject: Re: [webthree-umbrella] AlethOne (#368)

Most probably a duplicate of #363
Does restarting AlethOne fix it?—

**Comment by sjaith** [comment]
Hi Mr. Summerwill,
Thank you, I really appreciate your help.  OSX 10.11.3, NVIDIA GeForce GTX 780M 4096 MB.  I installed AlethOne, cpp-ethereum-1.2.2 OSX, from the 'Install the Aleth Miner' tab on the ethereum.org homepage.  I have restarted the app many times.  I also rebooted the computer and have waited hours after restarting.  
AlethOne is still stuck on 1150006, the only thing that changes is the time of the 'New block #1150006.'  The time changes to whatever time I open AlethOne.  
Please let me know if you need more information.Thanks,Steve

```
  From: Bob Summerwill <notifications@github.com>
```

 To: ethereum/webthree-umbrella webthree-umbrella@noreply.github.com 
Cc: Steve Austin sjaith@yahoo.com
 Sent: Thursday, March 17, 2016 1:13 PM
 Subject: Re: [webthree-umbrella] AlethOne (#368)

Hey @sjaith!
We need a lot more information than this to be able to do anything, I'm afraid.What OS? What version? Did you built it yourself? Use installer?What you done to try to resolve it? Have you shut down and restarted the app? Tried rebooting? Tried waiting? Thanks!—

**Comment by sjaith** [comment]
Now my mist wallet won't even load, stuck on 'Processing blocks, please wait...' when I open it.  I'm guessing it's related to AlethOne and rebooting the computer.  My mist wallet hasn't synced since I rebooted my computer earlier today.  I'm just trying to provide feedback. Please let me know if you want any more info or if I am dragging you down, cuz I can wait.
ThanksSteve

```
  From: Bob Summerwill <notifications@github.com>
```

 To: ethereum/webthree-umbrella webthree-umbrella@noreply.github.com 
Cc: Steve Austin sjaith@yahoo.com
 Sent: Thursday, March 17, 2016 1:13 PM
 Subject: Re: [webthree-umbrella] AlethOne (#368)

Hey @sjaith!
We need a lot more information than this to be able to do anything, I'm afraid.What OS? What version? Did you built it yourself? Use installer?What you done to try to resolve it? Have you shut down and restarted the app? Tried rebooting? Tried waiting? Thanks!—

**Comment by BalazsJN** [comment]
The same problem occurred on win 7! The Ethereum wallet don't sync! It is downloading block 1,150,006 almost a day, and I can't use my account!

**Comment by BalazsJN** [comment]
Is there any solution?

**Comment by chriseth** [comment]
Probably fixed here: https://github.com/ethereum/libethereum/pull/208

**Comment by bobsummerwill** [comment]
Hey @sjaith,

AlethOne and AlethZero are slated for death (https://blog.ethereum.org/2016/02/12/ethereum-dev-update-c-roadmap/), and it increasingly looks like we need to put a bullet in their backs right now and remove that prominent link to "One Click Miner" on http://ethereum.org.     Sorry that you were a victim of their imminent demise.

I would recommend that you consider switching to ethminer+geth, which is what nearly all miners appear to be doing, and also to check out the https://github.com/Genoil/cpp-ethereum/ ethminer fork, which appears to be the leading solution.

Also check out the side-bar on http://reddit.com/r/etherminer for the guides there.

Good luck.  Please do let us know if you find a working setup and let us know what you did.   Thanks!

With regard to Mist.    If you have a running node then Mist will attach to that.    If you want to put mining aside for a bit, just stop your AlethOne running and launch Mist.    It will start an internal geth node (which will need to do a full sync), but that can run without any AlethOne interference.   Or, if you plan to do ethminer+geth, you can just install geth and run that standalone, and then start Mist and it will attach to that.   You can share that geth node for your GUI walleting and your mining

**Comment by bobsummerwill** [comment]
Hey @BalazsJN,
For your issue, which appears unrelated, I would recommend you stop your Mist, reboot your machine and start again.   Are you running an AlethOne node, and the Wallet is attaching to that?   Are you trying to mine as well?

**Comment by sjaith** [comment]
Thanks Bob, I really appreciate the help.
Mist was easy.  I just uninstalled AlethZero, AlethOne, and Mix; then rebooted, reinstalled Mist, and rebooted.  Mist works.  However, I still cannot mine.  Sorry to be a pain, I'm not trying to be selfish by mining, just trying to decentralize!  Still no luck mining.  Mist works though.  I will keep trying and any suggestions would be cool.  I tried Genoli/cpp-ethereum to no avail, but maybe I'm missing something.

Steve

```
  From: Bob Summerwill <notifications@github.com>
```

 To: ethereum/webthree-umbrella webthree-umbrella@noreply.github.com 
Cc: Steve Austin sjaith@yahoo.com
 Sent: Saturday, March 19, 2016 9:10 AM
 Subject: Re: [webthree-umbrella] AlethOne stuck at block 1150006 (#368)

Hey @sjaith,AlethOne and AlethZero are slated for death (https://blog.ethereum.org/2016/02/12/ethereum-dev-update-c-roadmap/), and it increasingly looks like we need to put a bullet in their backs right now and remove that prominent link to "One Click Miner" on http://ethereum.org. Sorry that you were a victim of their imminent demise.I would recommend that you consider switching to ethminer+geth, which is what nearly all miners appear to be doing, and also to check out the https://github.com/Genoil/cpp-ethereum/ ethminer fork, which appears to be the leading solution.Also check out the side-bar on http://reddit.com/r/etherminer for the guides there.Good luck. Please do let us know if you find a working setup and let us know what you did. Thanks!With regard to Mist. If you have a running node then Mist will attach to that. If you want to put mining aside for a bit, just stop your AlethOne running and launch Mist. It will start an internal geth node (which will need to do a full sync), but that can run without any AlethOne interference. Or, if you plan to do ethminer+geth, you can just install geth and run that standalone, and then start Mist and it will attach to that. You can share that geth node for your GUI walleting and your mining—

**Comment by bobsummerwill** [comment]
"I tried Genoli/cpp-ethereum to no avail"

Connected to what node?    ethminer+geth seems to be the "winner" for most people.   If your Mist is working standalone then that would be running with the internal geth-1.3.5.

Could you try the ethminer from Genoil AFTER your Mist has synced (and is still running)?

**Comment by bobsummerwill** [comment]
Closing, because AlethOne will be killed very soon.
